
#include "rstack.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>

#undef NDEBUG

/** MAKRA SKRACAJĄCE IMPLEMENTACJĘ TESTÓW **/

// To są możliwe wyniki testu.
#define PASS 0
#define FAIL 1
#define WRONG_TEST 2

// Oblicza liczbę elementów tablicy x.
#define SIZE(x) (sizeof x / sizeof x[0])

#define ASSERT(f)            \
  do {                       \
    if (!(f))                \
      return FAIL;           \
  } while (0)

#define ASSERT_RESULT(c, f, ...)          \
  do {                                    \
    result_t r = c;                       \
    if (r.flag != (f))                    \
      return FAIL;                        \
    if ((f) && r.value != __VA_ARGS__ -0) \
      return FAIL;                        \
  } while (0)

#define CHECK_IF_NO_ERROR(f) \
  do {                       \
    if ((f) != 0)            \
      return FAIL;           \
  } while (0)

#define V(code, where) (((unsigned long)code) << (3 * where))

int test45(void) {
rstack_t* rs0 = rstack_new();
rstack_t* rs1 = rstack_new();
rstack_t* rs2 = rstack_new();
rstack_t* rs3 = rstack_new();
rstack_t* rs4 = rstack_new();
rstack_t* rs5 = rstack_new();
rstack_t* rs6 = rstack_new();
rstack_t* rs7 = rstack_new();
rstack_t* rs8 = rstack_new();
rstack_t* rs9 = rstack_new();
rstack_t* rs10 = rstack_new();
rstack_t* rs11 = rstack_new();
rstack_t* rs12 = rstack_new();
rstack_t* rs13 = rstack_new();
rstack_t* rs14 = rstack_new();
rstack_t* rs15 = rstack_new();
rstack_t* rs16 = rstack_new();
rstack_t* rs17 = rstack_new();
rstack_t* rs18 = rstack_new();
rstack_t* rs19 = rstack_new();
rstack_t* rs20 = rstack_new();
rstack_t* rs21 = rstack_new();
rstack_t* rs22 = rstack_new();
rstack_t* rs23 = rstack_new();
rstack_t* rs24 = rstack_new();
rstack_t* rs25 = rstack_new();
rstack_t* rs26 = rstack_new();
rstack_t* rs27 = rstack_new();
rstack_t* rs28 = rstack_new();
rstack_t* rs29 = rstack_new();
rstack_t* rs30 = rstack_new();
rstack_t* rs31 = rstack_new();
rstack_t* rs32 = rstack_new();
rstack_t* rs33 = rstack_new();
rstack_t* rs34 = rstack_new();
rstack_t* rs35 = rstack_new();
rstack_t* rs36 = rstack_new();
rstack_t* rs37 = rstack_new();
rstack_t* rs38 = rstack_new();
rstack_t* rs39 = rstack_new();
rstack_t* rs40 = rstack_new();
rstack_t* rs41 = rstack_new();
rstack_t* rs42 = rstack_new();
rstack_t* rs43 = rstack_new();
rstack_t* rs44 = rstack_new();
rstack_t* rs45 = rstack_new();
rstack_t* rs46 = rstack_new();
rstack_t* rs47 = rstack_new();
rstack_t* rs48 = rstack_new();
rstack_t* rs49 = rstack_new();
rstack_t* rs50 = rstack_new();
rstack_t* rs51 = rstack_new();
rstack_t* rs52 = rstack_new();
rstack_t* rs53 = rstack_new();
rstack_t* rs54 = rstack_new();
rstack_t* rs55 = rstack_new();
rstack_t* rs56 = rstack_new();
rstack_t* rs57 = rstack_new();
rstack_t* rs58 = rstack_new();
rstack_t* rs59 = rstack_new();
rstack_t* rs60 = rstack_new();
rstack_t* rs61 = rstack_new();
rstack_t* rs62 = rstack_new();
rstack_t* rs63 = rstack_new();
rstack_t* rs64 = rstack_new();
rstack_t* rs65 = rstack_new();
rstack_t* rs66 = rstack_new();
rstack_t* rs67 = rstack_new();
rstack_t* rs68 = rstack_new();
rstack_t* rs69 = rstack_new();
rstack_t* rs70 = rstack_new();
rstack_t* rs71 = rstack_new();
rstack_t* rs72 = rstack_new();
rstack_t* rs73 = rstack_new();
rstack_t* rs74 = rstack_new();
rstack_t* rs75 = rstack_new();
rstack_t* rs76 = rstack_new();
rstack_t* rs77 = rstack_new();
rstack_t* rs78 = rstack_new();
rstack_t* rs79 = rstack_new();
rstack_t* rs80 = rstack_new();
rstack_t* rs81 = rstack_new();
rstack_t* rs82 = rstack_new();
rstack_t* rs83 = rstack_new();
rstack_t* rs84 = rstack_new();
rstack_t* rs85 = rstack_new();
rstack_t* rs86 = rstack_new();
rstack_t* rs87 = rstack_new();
rstack_t* rs88 = rstack_new();
rstack_t* rs89 = rstack_new();
rstack_t* rs90 = rstack_new();
rstack_t* rs91 = rstack_new();
rstack_t* rs92 = rstack_new();
rstack_t* rs93 = rstack_new();
rstack_t* rs94 = rstack_new();
rstack_t* rs95 = rstack_new();
rstack_t* rs96 = rstack_new();
rstack_t* rs97 = rstack_new();
rstack_t* rs98 = rstack_new();
rstack_t* rs99 = rstack_new();
ASSERT_RESULT(rstack_front(rs66), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_9.result.out", rs62));
ASSERT_RESULT(rstack_front(rs23), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs61, rs45));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs1));
ASSERT_RESULT(rstack_front(rs66), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs85));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs95));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs99));
ASSERT(rstack_empty(rs86) == true);
ASSERT_RESULT(rstack_front(rs99), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs86));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs64, rs22));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs79));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs88, rs64));
ASSERT(rstack_empty(rs14) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs30));
ASSERT_RESULT(rstack_front(rs31), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs51, rs94));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs79, rs5));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_1.result.out", rs89));
ASSERT_RESULT(rstack_front(rs53), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs25));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs82, rs95));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs78));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs78, rs68));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_176.result.out", rs69));
ASSERT(rstack_empty(rs82) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs69));
ASSERT_RESULT(rstack_front(rs41), false, 0UL);
ASSERT_RESULT(rstack_front(rs40), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs30));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_14.result.out", rs9));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_98.result.out", rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs20, rs45));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs51));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs80, rs82));
ASSERT(rstack_empty(rs74) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs85));
ASSERT_RESULT(rstack_front(rs20), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs71, rs65));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs33));
ASSERT_RESULT(rstack_front(rs95), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs63, rs26));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs39));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs58));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_136.result.out", rs59));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs56, rs25));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs94, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs12));
ASSERT(rstack_empty(rs56) == true);
ASSERT_RESULT(rstack_front(rs36), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_170.result.out", rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs75, rs98));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs61, rs24));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_57.result.out", rs29));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs56, rs44));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs77));
ASSERT(rstack_empty(rs92) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs93));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_32.result.out", rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs75, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs70, rs33));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_148.result.out", rs5));
ASSERT_RESULT(rstack_front(rs15), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs72, rs53));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_137.result.out", rs43));
ASSERT_RESULT(rstack_front(rs29), false, 0UL);
ASSERT_RESULT(rstack_front(rs82), false, 0UL);
ASSERT_RESULT(rstack_front(rs54), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_142.result.out", rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs61, rs72));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs87, rs61));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_162.result.out", rs37));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs48));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_54.result.out", rs25));
ASSERT_RESULT(rstack_front(rs73), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs70, rs68));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_138.result.out", rs49));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_8.result.out", rs81));
ASSERT_RESULT(rstack_front(rs61), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_44.result.out", rs43));
ASSERT(rstack_empty(rs87) == true);
ASSERT_RESULT(rstack_front(rs11), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs47));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_61.result.out", rs7));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_11.result.out", rs64));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs61));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_23.result.out", rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs73, rs57));
ASSERT_RESULT(rstack_front(rs18), false, 0UL);
ASSERT_RESULT(rstack_front(rs53), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs81));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs35));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_114.result.out", rs8));
ASSERT_RESULT(rstack_front(rs99), false, 0UL);
ASSERT_RESULT(rstack_front(rs61), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs87, rs81));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs77));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_62.result.out", rs84));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs74, rs60));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs28));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs81, rs48));
ASSERT_RESULT(rstack_front(rs59), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs78));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs97, rs30));
ASSERT(rstack_empty(rs11) == true);
ASSERT_RESULT(rstack_front(rs72), false, 0UL);
ASSERT_RESULT(rstack_front(rs35), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs7));
ASSERT_RESULT(rstack_front(rs32), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs39));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs57, rs93));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_26.result.out", rs47));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs89, rs53));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs74, rs45));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_97.result.out", rs24));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_66.result.out", rs80));
ASSERT_RESULT(rstack_front(rs51), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs77, rs59));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs63, rs94));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_77.result.out", rs55));
ASSERT_RESULT(rstack_front(rs18), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs77));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_19.result.out", rs57));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs79, rs11));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_160.result.out", rs44));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs26));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs9));
ASSERT_RESULT(rstack_front(rs28), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_75.result.out", rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs50, rs9));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_109.result.out", rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs39, rs12));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_199.result.out", rs82));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs85));
ASSERT(rstack_empty(rs32) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs39, rs34));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs91));
ASSERT(rstack_empty(rs79) == true);
ASSERT_RESULT(rstack_front(rs56), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs63, rs2));
ASSERT_RESULT(rstack_front(rs72), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs87));
ASSERT(rstack_empty(rs52) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_178.result.out", rs61));
ASSERT_RESULT(rstack_front(rs93), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_18.result.out", rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs75, rs59));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs72, rs59));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs62, rs59));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs87, rs64));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_133.result.out", rs49));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs97, rs69));
ASSERT_RESULT(rstack_front(rs40), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_74.result.out", rs9));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_125.result.out", rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs11));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs0));
ASSERT_RESULT(rstack_front(rs88), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs98, rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs98, rs25));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_73.result.out", rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs12));
ASSERT_RESULT(rstack_front(rs39), false, 0UL);
ASSERT_RESULT(rstack_front(rs52), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs79));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_53.result.out", rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs39));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs5));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_177.result.out", rs58));
ASSERT_RESULT(rstack_front(rs17), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_157.result.out", rs59));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_102.result.out", rs94));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs83));
ASSERT(rstack_empty(rs80) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs2));
ASSERT_RESULT(rstack_front(rs87), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs76, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs85));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs91, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs83, rs85));
ASSERT_RESULT(rstack_front(rs31), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_131.result.out", rs50));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs93, rs83));
ASSERT_RESULT(rstack_front(rs81), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs74));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs54, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs18));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_192.result.out", rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs84, rs75));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs5));
ASSERT_RESULT(rstack_front(rs47), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs50, rs72));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs64, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs91, rs37));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_128.result.out", rs16));
ASSERT(rstack_empty(rs14) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs69, rs46));
ASSERT_RESULT(rstack_front(rs34), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs78));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_83.result.out", rs65));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_150.result.out", rs88));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs54));
ASSERT_RESULT(rstack_front(rs64), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs90, rs37));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs60, rs28));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs60, rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs96, rs17));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs88, rs47));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs75, rs81));
ASSERT_RESULT(rstack_front(rs81), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs93, rs8));
ASSERT(rstack_empty(rs25) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_21.result.out", rs40));
ASSERT(rstack_empty(rs62) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_164.result.out", rs68));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_92.result.out", rs93));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_126.result.out", rs97));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs29));
ASSERT_RESULT(rstack_front(rs53), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs91));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs75, rs89));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs8));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_91.result.out", rs94));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_38.result.out", rs24));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_93.result.out", rs58));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs90, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs63, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs78));
ASSERT(rstack_empty(rs25) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_47.result.out", rs49));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs59, rs61));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs15));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_143.result.out", rs36));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs65));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs95));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_29.result.out", rs13));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs57, rs20));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_188.result.out", rs25));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_43.result.out", rs51));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs61, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs86, rs16));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs26));
ASSERT_RESULT(rstack_front(rs52), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs23));
ASSERT(rstack_empty(rs94) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_195.result.out", rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs84, rs87));
ASSERT_RESULT(rstack_front(rs74), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs36));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_187.result.out", rs43));
ASSERT_RESULT(rstack_front(rs90), false, 0UL);
ASSERT_RESULT(rstack_front(rs37), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs98, rs77));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_149.result.out", rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs66, rs83));
ASSERT_RESULT(rstack_front(rs97), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs62, rs49));
ASSERT_RESULT(rstack_front(rs75), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs93, rs76));
ASSERT(rstack_empty(rs96) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs98, rs5));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_151.result.out", rs83));
ASSERT_RESULT(rstack_front(rs70), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs55, rs94));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_49.result.out", rs11));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs80, rs42));
ASSERT(rstack_empty(rs70) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_80.result.out", rs25));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_33.result.out", rs26));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_89.result.out", rs67));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs76, rs87));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_34.result.out", rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs29));
ASSERT(rstack_empty(rs81) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs49));
ASSERT_RESULT(rstack_front(rs9), false, 0UL);
ASSERT_RESULT(rstack_front(rs57), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_127.result.out", rs44));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs54));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_189.result.out", rs90));
ASSERT(rstack_empty(rs33) == true);
ASSERT_RESULT(rstack_front(rs56), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs52, rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs77, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs92, rs50));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs59));
ASSERT_RESULT(rstack_front(rs98), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs67, rs80));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs59));
ASSERT_RESULT(rstack_front(rs5), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs88, rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs84));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs51, rs36));
ASSERT(rstack_empty(rs5) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs84));
ASSERT_RESULT(rstack_front(rs76), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_155.result.out", rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs93));
ASSERT_RESULT(rstack_front(rs19), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs70, rs34));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs99, rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs47));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs55, rs75));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs67, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs80));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_154.result.out", rs56));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs52, rs7));
ASSERT_RESULT(rstack_front(rs91), false, 0UL);
ASSERT_RESULT(rstack_front(rs58), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs86));
ASSERT_RESULT(rstack_front(rs73), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs92, rs44));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_145.result.out", rs9));
ASSERT_RESULT(rstack_front(rs73), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_116.result.out", rs91));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs78, rs69));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_183.result.out", rs53));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs87));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs93, rs61));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs91, rs56));
ASSERT(rstack_empty(rs16) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_191.result.out", rs18));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_156.result.out", rs5));
ASSERT(rstack_empty(rs68) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs80));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_161.result.out", rs34));
ASSERT_RESULT(rstack_front(rs55), false, 0UL);
ASSERT(rstack_empty(rs75) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs79, rs61));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs97, rs37));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_166.result.out", rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs81, rs81));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_85.result.out", rs22));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs52, rs68));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs97, rs45));
ASSERT_RESULT(rstack_front(rs44), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs55, rs11));
ASSERT(rstack_empty(rs88) == true);
ASSERT_RESULT(rstack_front(rs11), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs40));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_107.result.out", rs42));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_22.result.out", rs85));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs52));
ASSERT(rstack_empty(rs37) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs52, rs9));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs69, rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs98, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs46));
ASSERT_RESULT(rstack_front(rs9), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_172.result.out", rs70));
ASSERT_RESULT(rstack_front(rs63), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs61, rs78));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_113.result.out", rs42));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs53));
ASSERT_RESULT(rstack_front(rs5), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs85, rs90));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs70, rs2));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_5.result.out", rs54));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs95));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs78, rs75));
ASSERT(rstack_empty(rs50) == true);
ASSERT(rstack_empty(rs73) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs70, rs26));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs61));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs85));
ASSERT_RESULT(rstack_front(rs83), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs8));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_167.result.out", rs98));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs77));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs90));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs96));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs20));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_16.result.out", rs95));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs66));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs62, rs10));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs60));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs81));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs63, rs8));
ASSERT_RESULT(rstack_front(rs12), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs80));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs91, rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs53));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs73));
ASSERT_RESULT(rstack_front(rs12), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs53, rs84));
ASSERT_RESULT(rstack_front(rs92), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs68, rs25));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_103.result.out", rs39));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs56, rs53));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs78));
ASSERT_RESULT(rstack_front(rs10), false, 0UL);
ASSERT(rstack_empty(rs0) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs75));
ASSERT_RESULT(rstack_front(rs36), false, 0UL);
ASSERT_RESULT(rstack_front(rs94), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_117.result.out", rs55));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs56, rs83));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs91));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs54, rs37));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs90, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs84, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs19));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_106.result.out", rs79));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs2));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_101.result.out", rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs73, rs96));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs88, rs26));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs72));
ASSERT_RESULT(rstack_front(rs45), false, 0UL);
ASSERT(rstack_empty(rs53) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs6));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_69.result.out", rs57));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs43));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs57, rs83));
ASSERT_RESULT(rstack_front(rs75), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs46));
ASSERT_RESULT(rstack_front(rs13), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs16));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs88, rs66));
ASSERT(rstack_empty(rs23) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_105.result.out", rs96));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs55, rs81));
ASSERT_RESULT(rstack_front(rs81), false, 0UL);
ASSERT_RESULT(rstack_front(rs12), false, 0UL);
ASSERT_RESULT(rstack_front(rs23), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs42));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs79, rs99));
ASSERT_RESULT(rstack_front(rs50), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs77, rs81));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs70));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_124.result.out", rs47));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs93));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_193.result.out", rs76));
ASSERT_RESULT(rstack_front(rs24), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs19));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_153.result.out", rs62));
ASSERT_RESULT(rstack_front(rs56), false, 0UL);
ASSERT(rstack_empty(rs32) == true);
ASSERT(rstack_empty(rs52) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs53));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_88.result.out", rs64));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs50));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs85));
ASSERT_RESULT(rstack_front(rs38), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs89));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_180.result.out", rs89));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs96, rs66));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs91, rs58));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs93, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs85, rs34));
ASSERT(rstack_empty(rs27) == true);
ASSERT_RESULT(rstack_front(rs59), false, 0UL);
ASSERT(rstack_empty(rs8) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs88, rs72));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs47));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_159.result.out", rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs29));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs60, rs95));
ASSERT_RESULT(rstack_front(rs16), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs73, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs73, rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs34));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_13.result.out", rs84));
ASSERT_RESULT(rstack_front(rs37), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs58));
ASSERT_RESULT(rstack_front(rs47), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs87, rs5));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_87.result.out", rs86));
ASSERT_RESULT(rstack_front(rs95), false, 0UL);
ASSERT(rstack_empty(rs13) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_76.result.out", rs17));
ASSERT_RESULT(rstack_front(rs16), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs70, rs64));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_37.result.out", rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs88, rs66));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs62, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs88, rs78));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs50, rs79));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs10));
ASSERT_RESULT(rstack_front(rs10), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_30.result.out", rs89));
ASSERT_RESULT(rstack_front(rs11), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs79, rs70));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs13));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs32));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_4.result.out", rs10));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs54));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs88, rs79));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_95.result.out", rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs82, rs54));
ASSERT_RESULT(rstack_front(rs16), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs98, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs72, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs43));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs82, rs52));
ASSERT_RESULT(rstack_front(rs9), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_135.result.out", rs31));
ASSERT(rstack_empty(rs90) == true);
ASSERT_RESULT(rstack_front(rs15), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs81, rs67));
ASSERT(rstack_empty(rs85) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_52.result.out", rs53));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_31.result.out", rs3));
ASSERT_RESULT(rstack_front(rs58), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_169.result.out", rs68));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs54, rs5));
ASSERT_RESULT(rstack_front(rs69), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs76, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs53, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs65, rs38));
ASSERT_RESULT(rstack_front(rs73), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs65, rs84));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs26));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_84.result.out", rs90));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs31, rs30));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs86, rs77));
ASSERT_RESULT(rstack_front(rs70), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_120.result.out", rs14));
ASSERT(rstack_empty(rs56) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_132.result.out", rs54));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_111.result.out", rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs54, rs24));
ASSERT_RESULT(rstack_front(rs17), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs3));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_72.result.out", rs91));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs61, rs26));
ASSERT_RESULT(rstack_front(rs2), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs84));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs51));
ASSERT_RESULT(rstack_front(rs87), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_194.result.out", rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs85, rs49));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_179.result.out", rs72));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs48));
ASSERT_RESULT(rstack_front(rs29), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs92, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs95, rs63));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs45));
ASSERT(rstack_empty(rs72) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs55, rs36));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs91, rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs72));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs63, rs19));
ASSERT(rstack_empty(rs77) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs47));
ASSERT_RESULT(rstack_front(rs77), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs91, rs29));
ASSERT_RESULT(rstack_front(rs5), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_99.result.out", rs85));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs26));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_39.result.out", rs64));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs83, rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs63));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs96));
ASSERT_RESULT(rstack_front(rs51), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_67.result.out", rs78));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs90, rs64));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs47));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_17.result.out", rs3));
ASSERT_RESULT(rstack_front(rs53), false, 0UL);
ASSERT(rstack_empty(rs28) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_60.result.out", rs57));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs35));
ASSERT(rstack_empty(rs34) == true);
ASSERT_RESULT(rstack_front(rs24), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_71.result.out", rs45));
ASSERT_RESULT(rstack_front(rs11), false, 0UL);
ASSERT(rstack_empty(rs72) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_129.result.out", rs88));
ASSERT_RESULT(rstack_front(rs1), false, 0UL);
ASSERT(rstack_empty(rs78) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs82));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs60, rs25));
ASSERT_RESULT(rstack_front(rs36), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs91));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs60, rs25));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs96, rs35));
ASSERT(rstack_empty(rs76) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_141.result.out", rs95));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs53, rs29));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs90, rs26));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_10.result.out", rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs99, rs59));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs15));
ASSERT_RESULT(rstack_front(rs98), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs39, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs50, rs3));
ASSERT_RESULT(rstack_front(rs95), false, 0UL);
ASSERT(rstack_empty(rs37) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs82, rs83));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs88, rs93));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs77, rs61));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs22));
ASSERT_RESULT(rstack_front(rs18), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_70.result.out", rs63));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs26));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_0.result.out", rs51));
ASSERT_RESULT(rstack_front(rs33), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs93));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs37));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs87, rs71));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs88, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs69, rs6));
ASSERT_RESULT(rstack_front(rs73), false, 0UL);
ASSERT_RESULT(rstack_front(rs22), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs94));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs79));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs28));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_81.result.out", rs37));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs25));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_168.result.out", rs83));
ASSERT_RESULT(rstack_front(rs46), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs97));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs92));
ASSERT_RESULT(rstack_front(rs84), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs37));
ASSERT_RESULT(rstack_front(rs50), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs69));
ASSERT_RESULT(rstack_front(rs77), false, 0UL);
ASSERT_RESULT(rstack_front(rs57), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_140.result.out", rs91));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs65, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs91));
ASSERT_RESULT(rstack_front(rs95), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs64));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs20, rs4));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_3.result.out", rs24));
ASSERT_RESULT(rstack_front(rs4), false, 0UL);
ASSERT_RESULT(rstack_front(rs12), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs93));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_78.result.out", rs75));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs62, rs76));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_65.result.out", rs33));
ASSERT_RESULT(rstack_front(rs16), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_15.result.out", rs25));
ASSERT(rstack_empty(rs73) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_59.result.out", rs20));
ASSERT_RESULT(rstack_front(rs72), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_7.result.out", rs58));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs92, rs79));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs58, rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs31, rs24));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_175.result.out", rs91));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs78, rs89));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs78, rs42));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs61, rs29));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_139.result.out", rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs27));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_63.result.out", rs58));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_174.result.out", rs52));
ASSERT_RESULT(rstack_front(rs92), false, 0UL);
ASSERT_RESULT(rstack_front(rs9), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs14));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_186.result.out", rs39));
ASSERT(rstack_empty(rs19) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs64, rs68));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_134.result.out", rs64));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs83, rs81));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs97));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs82, rs97));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_104.result.out", rs87));
ASSERT_RESULT(rstack_front(rs11), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs99));
ASSERT_RESULT(rstack_front(rs8), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs31, rs17));
ASSERT_RESULT(rstack_front(rs86), false, 0UL);
ASSERT_RESULT(rstack_front(rs22), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs9));
ASSERT_RESULT(rstack_front(rs6), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_118.result.out", rs23));
ASSERT_RESULT(rstack_front(rs16), false, 0UL);
ASSERT_RESULT(rstack_front(rs79), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs55, rs78));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs89, rs39));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs79, rs38));
ASSERT(rstack_empty(rs97) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs69, rs53));
ASSERT_RESULT(rstack_front(rs53), false, 0UL);
ASSERT_RESULT(rstack_front(rs13), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_112.result.out", rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs57));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs52));
ASSERT_RESULT(rstack_front(rs73), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_58.result.out", rs65));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_79.result.out", rs2));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_50.result.out", rs89));
ASSERT_RESULT(rstack_front(rs43), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_163.result.out", rs85));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs61, rs70));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs92));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_130.result.out", rs45));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs94));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs39));
ASSERT_RESULT(rstack_front(rs19), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_86.result.out", rs95));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs94));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs58));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs76, rs47));
ASSERT_RESULT(rstack_front(rs99), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs82, rs74));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_64.result.out", rs18));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_115.result.out", rs66));
ASSERT_RESULT(rstack_front(rs36), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs70, rs85));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs90, rs26));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs80));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_40.result.out", rs61));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs85));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_46.result.out", rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs72));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs20, rs48));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_171.result.out", rs99));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs81, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs91));
ASSERT(rstack_empty(rs14) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_82.result.out", rs65));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs93, rs99));
ASSERT_RESULT(rstack_front(rs88), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_173.result.out", rs64));
ASSERT_RESULT(rstack_front(rs96), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_184.result.out", rs12));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_12.result.out", rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs54, rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs67, rs10));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs75, rs55));
ASSERT(rstack_empty(rs97) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_94.result.out", rs61));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs90, rs65));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_121.result.out", rs86));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs11, rs61));
ASSERT(rstack_empty(rs85) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs91));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs98, rs59));
ASSERT_RESULT(rstack_front(rs41), false, 0UL);
ASSERT_RESULT(rstack_front(rs78), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs64));
ASSERT_RESULT(rstack_front(rs22), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs85, rs84));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs83, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs72));
ASSERT(rstack_empty(rs3) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs85));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_42.result.out", rs26));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs76, rs60));
ASSERT_RESULT(rstack_front(rs24), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_190.result.out", rs20));
ASSERT(rstack_empty(rs66) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_25.result.out", rs57));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs73));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs88, rs7));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_27.result.out", rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs56, rs11));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_197.result.out", rs53));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs39));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_165.result.out", rs12));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_90.result.out", rs13));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs21));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs58, rs75));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs89, rs16));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_123.result.out", rs20));
ASSERT(rstack_empty(rs94) == true);
ASSERT_RESULT(rstack_front(rs81), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs77, rs81));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_56.result.out", rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs59));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs46));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs85, rs79));
ASSERT_RESULT(rstack_front(rs19), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs71));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs60, rs97));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs73, rs39));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_51.result.out", rs19));
ASSERT_RESULT(rstack_front(rs14), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs88));
ASSERT_RESULT(rstack_front(rs78), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_144.result.out", rs75));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs88, rs48));
ASSERT_RESULT(rstack_front(rs51), false, 0UL);
ASSERT_RESULT(rstack_front(rs9), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs85));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs83, rs46));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs71, rs53));
ASSERT_RESULT(rstack_front(rs66), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs53, rs43));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_45.result.out", rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs51, rs4));
ASSERT_RESULT(rstack_front(rs56), false, 0UL);
ASSERT_RESULT(rstack_front(rs45), false, 0UL);
ASSERT(rstack_empty(rs16) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_152.result.out", rs62));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_48.result.out", rs83));
ASSERT_RESULT(rstack_front(rs12), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs65, rs58));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs89, rs46));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_2.result.out", rs37));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_41.result.out", rs28));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_119.result.out", rs24));
ASSERT(rstack_empty(rs17) == true);
ASSERT(rstack_empty(rs51) == true);
ASSERT_RESULT(rstack_front(rs67), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs86));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_198.result.out", rs52));
ASSERT(rstack_empty(rs62) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_182.result.out", rs64));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs45));
ASSERT_RESULT(rstack_front(rs75), false, 0UL);
ASSERT_RESULT(rstack_front(rs99), false, 0UL);
ASSERT_RESULT(rstack_front(rs16), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs81, rs94));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs50, rs42));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs83, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs82, rs20));
ASSERT_RESULT(rstack_front(rs22), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs61, rs42));
ASSERT(rstack_empty(rs32) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs48));
ASSERT_RESULT(rstack_front(rs78), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs38));
ASSERT_RESULT(rstack_front(rs73), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs42));
ASSERT(rstack_empty(rs30) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs82, rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs96));
ASSERT_RESULT(rstack_front(rs66), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs75, rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs16));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_68.result.out", rs84));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs68, rs46));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs99, rs47));
ASSERT_RESULT(rstack_front(rs69), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_28.result.out", rs0));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_35.result.out", rs57));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_110.result.out", rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs7));
ASSERT_RESULT(rstack_front(rs47), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_6.result.out", rs65));
ASSERT(rstack_empty(rs72) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs95));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs87));
ASSERT_RESULT(rstack_front(rs25), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_108.result.out", rs87));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs52));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs77));
ASSERT(rstack_empty(rs16) == true);
ASSERT(rstack_empty(rs29) == true);
ASSERT(rstack_empty(rs49) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs80));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs34));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs62, rs16));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_147.result.out", rs53));
ASSERT(rstack_empty(rs64) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs98, rs55));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs92));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs90));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_20.result.out", rs96));
ASSERT_RESULT(rstack_front(rs71), false, 0UL);
ASSERT_RESULT(rstack_front(rs48), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs52));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_196.result.out", rs64));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_24.result.out", rs61));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_36.result.out", rs19));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_181.result.out", rs26));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_146.result.out", rs28));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs68));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs34, rs39));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs67, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs34));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs70, rs58));
ASSERT_RESULT(rstack_front(rs7), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_55.result.out", rs83));
ASSERT_RESULT(rstack_front(rs67), false, 0UL);
ASSERT_RESULT(rstack_front(rs19), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs93, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs30));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs80, rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs63, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs86, rs22));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs69, rs38));
ASSERT_RESULT(rstack_front(rs10), false, 0UL);
ASSERT(rstack_empty(rs54) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs30));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_122.result.out", rs45));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs70, rs56));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs86, rs97));
ASSERT_RESULT(rstack_front(rs87), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs53, rs95));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_158.result.out", rs82));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs89));
ASSERT_RESULT(rstack_front(rs50), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs83, rs97));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs54));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs92, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs66));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs73, rs49));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_100.result.out", rs16));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs98, rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs63, rs62));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs87));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs82, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs42));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs87, rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs72, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs84, rs77));
ASSERT(rstack_empty(rs81) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs86, rs43));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_185.result.out", rs60));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test45_96.result.out", rs85));
rstack_delete(rs0);
rstack_delete(rs1);
rstack_delete(rs2);
rstack_delete(rs3);
rstack_delete(rs4);
rstack_delete(rs5);
rstack_delete(rs6);
rstack_delete(rs7);
rstack_delete(rs8);
rstack_delete(rs9);
rstack_delete(rs10);
rstack_delete(rs11);
rstack_delete(rs12);
rstack_delete(rs13);
rstack_delete(rs14);
rstack_delete(rs15);
rstack_delete(rs16);
rstack_delete(rs17);
rstack_delete(rs18);
rstack_delete(rs19);
rstack_delete(rs20);
rstack_delete(rs21);
rstack_delete(rs22);
rstack_delete(rs23);
rstack_delete(rs24);
rstack_delete(rs25);
rstack_delete(rs26);
rstack_delete(rs27);
rstack_delete(rs28);
rstack_delete(rs29);
rstack_delete(rs30);
rstack_delete(rs31);
rstack_delete(rs32);
rstack_delete(rs33);
rstack_delete(rs34);
rstack_delete(rs35);
rstack_delete(rs36);
rstack_delete(rs37);
rstack_delete(rs38);
rstack_delete(rs39);
rstack_delete(rs40);
rstack_delete(rs41);
rstack_delete(rs42);
rstack_delete(rs43);
rstack_delete(rs44);
rstack_delete(rs45);
rstack_delete(rs46);
rstack_delete(rs47);
rstack_delete(rs48);
rstack_delete(rs49);
rstack_delete(rs50);
rstack_delete(rs51);
rstack_delete(rs52);
rstack_delete(rs53);
rstack_delete(rs54);
rstack_delete(rs55);
rstack_delete(rs56);
rstack_delete(rs57);
rstack_delete(rs58);
rstack_delete(rs59);
rstack_delete(rs60);
rstack_delete(rs61);
rstack_delete(rs62);
rstack_delete(rs63);
rstack_delete(rs64);
rstack_delete(rs65);
rstack_delete(rs66);
rstack_delete(rs67);
rstack_delete(rs68);
rstack_delete(rs69);
rstack_delete(rs70);
rstack_delete(rs71);
rstack_delete(rs72);
rstack_delete(rs73);
rstack_delete(rs74);
rstack_delete(rs75);
rstack_delete(rs76);
rstack_delete(rs77);
rstack_delete(rs78);
rstack_delete(rs79);
rstack_delete(rs80);
rstack_delete(rs81);
rstack_delete(rs82);
rstack_delete(rs83);
rstack_delete(rs84);
rstack_delete(rs85);
rstack_delete(rs86);
rstack_delete(rs87);
rstack_delete(rs88);
rstack_delete(rs89);
rstack_delete(rs90);
rstack_delete(rs91);
rstack_delete(rs92);
rstack_delete(rs93);
rstack_delete(rs94);
rstack_delete(rs95);
rstack_delete(rs96);
rstack_delete(rs97);
rstack_delete(rs98);
rstack_delete(rs99);
    
    return PASS;
}