
#include "rstack.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>

#undef NDEBUG

/** MAKRA SKRACAJĄCE IMPLEMENTACJĘ TESTÓW **/

// To są możliwe wyniki testu.
#define PASS 0
#define FAIL 1
#define WRONG_TEST 2

// Oblicza liczbę elementów tablicy x.
#define SIZE(x) (sizeof x / sizeof x[0])

#define ASSERT(f)            \
  do {                       \
    if (!(f))                \
      return FAIL;           \
  } while (0)

#define ASSERT_RESULT(c, f, ...)          \
  do {                                    \
    result_t r = c;                       \
    if (r.flag != (f))                    \
      return FAIL;                        \
    if ((f) && r.value != __VA_ARGS__ -0) \
      return FAIL;                        \
  } while (0)

#define CHECK_IF_NO_ERROR(f) \
  do {                       \
    if ((f) != 0)            \
      return FAIL;           \
  } while (0)

#define V(code, where) (((unsigned long)code) << (3 * where))

int test43(void) {
rstack_t* rs0 = rstack_new();
rstack_t* rs1 = rstack_new();
rstack_t* rs2 = rstack_new();
rstack_t* rs3 = rstack_new();
rstack_t* rs4 = rstack_new();
rstack_t* rs5 = rstack_new();
rstack_t* rs6 = rstack_new();
rstack_t* rs7 = rstack_new();
rstack_t* rs8 = rstack_new();
rstack_t* rs9 = rstack_new();
rstack_t* rs10 = rstack_new();
rstack_t* rs11 = rstack_new();
rstack_t* rs12 = rstack_new();
rstack_t* rs13 = rstack_new();
rstack_t* rs14 = rstack_new();
rstack_t* rs15 = rstack_new();
rstack_t* rs16 = rstack_new();
rstack_t* rs17 = rstack_new();
rstack_t* rs18 = rstack_new();
rstack_t* rs19 = rstack_new();
rstack_t* rs20 = rstack_new();
rstack_t* rs21 = rstack_new();
rstack_t* rs22 = rstack_new();
rstack_t* rs23 = rstack_new();
rstack_t* rs24 = rstack_new();
rstack_t* rs25 = rstack_new();
rstack_t* rs26 = rstack_new();
rstack_t* rs27 = rstack_new();
rstack_t* rs28 = rstack_new();
rstack_t* rs29 = rstack_new();
rstack_t* rs30 = rstack_new();
rstack_t* rs31 = rstack_new();
rstack_t* rs32 = rstack_new();
rstack_t* rs33 = rstack_new();
rstack_t* rs34 = rstack_new();
rstack_t* rs35 = rstack_new();
rstack_t* rs36 = rstack_new();
rstack_t* rs37 = rstack_new();
rstack_t* rs38 = rstack_new();
rstack_t* rs39 = rstack_new();
rstack_t* rs40 = rstack_new();
rstack_t* rs41 = rstack_new();
rstack_t* rs42 = rstack_new();
rstack_t* rs43 = rstack_new();
rstack_t* rs44 = rstack_new();
rstack_t* rs45 = rstack_new();
rstack_t* rs46 = rstack_new();
rstack_t* rs47 = rstack_new();
rstack_t* rs48 = rstack_new();
rstack_t* rs49 = rstack_new();
ASSERT(rstack_empty(rs27) == true);
ASSERT(rstack_empty(rs34) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs26));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs46));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs13));
ASSERT(rstack_empty(rs39) == true);
ASSERT(rstack_empty(rs18) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs31, rs2));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_27.result.out", rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs9));
ASSERT_RESULT(rstack_front(rs20), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs47));
ASSERT_RESULT(rstack_front(rs40), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs18));
ASSERT_RESULT(rstack_front(rs13), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs47));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs20));
ASSERT_RESULT(rstack_front(rs24), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_9.result.out", rs45));
ASSERT(rstack_empty(rs27) == true);
ASSERT_RESULT(rstack_front(rs35), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_22.result.out", rs26));
ASSERT_RESULT(rstack_front(rs30), false, 0UL);
ASSERT(rstack_empty(rs11) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs39, rs16));
ASSERT_RESULT(rstack_front(rs6), false, 0UL);
ASSERT(rstack_empty(rs22) == true);
ASSERT_RESULT(rstack_front(rs49), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_3.result.out", rs37));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs34));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs9));
ASSERT_RESULT(rstack_front(rs24), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs5));
ASSERT(rstack_empty(rs25) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs14));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_7.result.out", rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs45));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs30));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs11, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs9));
ASSERT(rstack_empty(rs37) == true);
ASSERT_RESULT(rstack_front(rs14), false, 0UL);
ASSERT(rstack_empty(rs3) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs26));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs9));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs37));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs9));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs48));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_36.result.out", rs47));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs11));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs11, rs39));
ASSERT_RESULT(rstack_front(rs4), false, 0UL);
ASSERT(rstack_empty(rs2) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs29));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs16));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs18));
ASSERT(rstack_empty(rs5) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs11, rs13));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs13));
ASSERT_RESULT(rstack_front(rs37), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs46));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs11));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_24.result.out", rs31));
ASSERT_RESULT(rstack_front(rs46), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs47));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs28));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs22));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_34.result.out", rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs34));
ASSERT_RESULT(rstack_front(rs38), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_45.result.out", rs21));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs26));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_2.result.out", rs2));
ASSERT_RESULT(rstack_front(rs43), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs18));
ASSERT_RESULT(rstack_front(rs29), false, 0UL);
ASSERT_RESULT(rstack_front(rs38), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs22));
ASSERT_RESULT(rstack_front(rs13), false, 0UL);
ASSERT(rstack_empty(rs4) == true);
ASSERT_RESULT(rstack_front(rs25), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs16));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_48.result.out", rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs42));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_25.result.out", rs13));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs11));
ASSERT(rstack_empty(rs28) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs42));
ASSERT_RESULT(rstack_front(rs10), false, 0UL);
ASSERT_RESULT(rstack_front(rs38), false, 0UL);
ASSERT_RESULT(rstack_front(rs44), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs49));
ASSERT_RESULT(rstack_front(rs25), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs34));
ASSERT(rstack_empty(rs0) == true);
ASSERT(rstack_empty(rs25) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs11, rs13));
ASSERT(rstack_empty(rs16) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs43));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs13));
ASSERT(rstack_empty(rs49) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs3));
ASSERT_RESULT(rstack_front(rs45), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs13));
ASSERT(rstack_empty(rs34) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs10));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs0));
ASSERT_RESULT(rstack_front(rs42), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs22));
ASSERT(rstack_empty(rs30) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_18.result.out", rs40));
ASSERT(rstack_empty(rs27) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs48));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_26.result.out", rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs29));
ASSERT_RESULT(rstack_front(rs14), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs7));
ASSERT(rstack_empty(rs6) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs34));
ASSERT(rstack_empty(rs47) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs45));
ASSERT_RESULT(rstack_front(rs32), false, 0UL);
ASSERT_RESULT(rstack_front(rs5), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs42));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs25));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs16));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_44.result.out", rs29));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs16));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs28));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs49));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs17));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs39));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs39, rs39));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs48));
ASSERT_RESULT(rstack_front(rs11), false, 0UL);
ASSERT(rstack_empty(rs43) == true);
ASSERT_RESULT(rstack_front(rs1), false, 0UL);
ASSERT_RESULT(rstack_front(rs25), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_35.result.out", rs23));
ASSERT(rstack_empty(rs13) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_29.result.out", rs0));
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs22));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs45));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs31));
ASSERT_RESULT(rstack_front(rs5), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs36));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs16));
ASSERT_RESULT(rstack_front(rs7), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs25));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs28));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs8));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_11.result.out", rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs12));
ASSERT_RESULT(rstack_front(rs3), false, 0UL);
ASSERT_RESULT(rstack_front(rs19), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_14.result.out", rs22));
ASSERT_RESULT(rstack_front(rs28), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs39));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_1.result.out", rs48));
ASSERT_RESULT(rstack_front(rs21), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs36));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs39, rs9));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs12));
ASSERT(rstack_empty(rs6) == true);
ASSERT(rstack_empty(rs43) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs35));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_32.result.out", rs38));
ASSERT(rstack_empty(rs46) == true);
ASSERT(rstack_empty(rs46) == true);
ASSERT_RESULT(rstack_front(rs31), false, 0UL);
ASSERT_RESULT(rstack_front(rs16), false, 0UL);
ASSERT_RESULT(rstack_front(rs30), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs30));
ASSERT_RESULT(rstack_front(rs36), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_33.result.out", rs27));
ASSERT_RESULT(rstack_front(rs16), false, 0UL);
ASSERT(rstack_empty(rs8) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs31, rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs12));
ASSERT_RESULT(rstack_front(rs39), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs25));
ASSERT(rstack_empty(rs34) == true);
ASSERT_RESULT(rstack_front(rs11), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs31));
ASSERT(rstack_empty(rs3) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_38.result.out", rs15));
ASSERT(rstack_empty(rs3) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_28.result.out", rs39));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs11, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs46));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs44));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs30));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_20.result.out", rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs36));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs44));
ASSERT(rstack_empty(rs9) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs29));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs37));
ASSERT(rstack_empty(rs41) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs20, rs13));
ASSERT_RESULT(rstack_front(rs36), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs34));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs10));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs16));
ASSERT_RESULT(rstack_front(rs34), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs47));
ASSERT(rstack_empty(rs16) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs42));
ASSERT_RESULT(rstack_front(rs30), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs42));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs34, rs47));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs13));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs3));
ASSERT_RESULT(rstack_front(rs9), false, 0UL);
ASSERT_RESULT(rstack_front(rs8), false, 0UL);
ASSERT_RESULT(rstack_front(rs32), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs43));
ASSERT_RESULT(rstack_front(rs6), false, 0UL);
ASSERT_RESULT(rstack_front(rs12), false, 0UL);
ASSERT(rstack_empty(rs13) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_37.result.out", rs14));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_16.result.out", rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs43));
ASSERT(rstack_empty(rs19) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs22));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs36));
ASSERT(rstack_empty(rs25) == true);
ASSERT(rstack_empty(rs47) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs34));
ASSERT_RESULT(rstack_front(rs23), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs39));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs3));
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
ASSERT_RESULT(rstack_front(rs21), false, 0UL);
ASSERT_RESULT(rstack_front(rs21), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs16));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_19.result.out", rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs42));
ASSERT_RESULT(rstack_front(rs43), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs8));
ASSERT_RESULT(rstack_front(rs5), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs8));
ASSERT_RESULT(rstack_front(rs1), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_5.result.out", rs39));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs44));
ASSERT_RESULT(rstack_front(rs36), false, 0UL);
ASSERT_RESULT(rstack_front(rs42), false, 0UL);
ASSERT(rstack_empty(rs34) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs9));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs42));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs16));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs17));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs38));
ASSERT_RESULT(rstack_front(rs16), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs28));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs30));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs44));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs46));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs38));
ASSERT(rstack_empty(rs18) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs32));
ASSERT(rstack_empty(rs21) == true);
ASSERT_RESULT(rstack_front(rs9), false, 0UL);
ASSERT_RESULT(rstack_front(rs6), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs17));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs31));
ASSERT_RESULT(rstack_front(rs18), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_43.result.out", rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs22));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs42));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs28));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_4.result.out", rs46));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs4));
ASSERT_RESULT(rstack_front(rs32), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs39));
ASSERT_RESULT(rstack_front(rs10), false, 0UL);
ASSERT_RESULT(rstack_front(rs41), false, 0UL);
ASSERT(rstack_empty(rs4) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs1));
ASSERT_RESULT(rstack_front(rs48), false, 0UL);
ASSERT(rstack_empty(rs18) == true);
ASSERT_RESULT(rstack_front(rs21), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs45));
ASSERT_RESULT(rstack_front(rs31), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_30.result.out", rs36));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs4));
ASSERT(rstack_empty(rs7) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs14));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_47.result.out", rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs14));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_31.result.out", rs11));
ASSERT(rstack_empty(rs31) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs45));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs28));
ASSERT(rstack_empty(rs18) == true);
ASSERT_RESULT(rstack_front(rs34), false, 0UL);
ASSERT_RESULT(rstack_front(rs25), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs39));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs20, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs4));
ASSERT_RESULT(rstack_front(rs6), false, 0UL);
ASSERT(rstack_empty(rs38) == true);
ASSERT_RESULT(rstack_front(rs31), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs13));
ASSERT_RESULT(rstack_front(rs40), false, 0UL);
ASSERT_RESULT(rstack_front(rs39), false, 0UL);
ASSERT_RESULT(rstack_front(rs5), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs20, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs44));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs28));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs45));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs17));
ASSERT(rstack_empty(rs9) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs22));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_42.result.out", rs25));
ASSERT(rstack_empty(rs40) == true);
ASSERT(rstack_empty(rs34) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs48));
ASSERT_RESULT(rstack_front(rs45), false, 0UL);
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs9));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs37));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs10));
ASSERT_RESULT(rstack_front(rs48), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs39));
ASSERT_RESULT(rstack_front(rs9), false, 0UL);
ASSERT(rstack_empty(rs11) == true);
ASSERT(rstack_empty(rs37) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs31, rs41));
ASSERT(rstack_empty(rs44) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs17));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs35));
ASSERT(rstack_empty(rs23) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs37));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs44));
ASSERT(rstack_empty(rs7) == true);
ASSERT_RESULT(rstack_front(rs36), false, 0UL);
ASSERT(rstack_empty(rs46) == true);
ASSERT(rstack_empty(rs18) == true);
ASSERT_RESULT(rstack_front(rs49), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs47));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs37));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_41.result.out", rs11));
ASSERT_RESULT(rstack_front(rs31), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs36));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs31, rs5));
ASSERT_RESULT(rstack_front(rs26), false, 0UL);
ASSERT_RESULT(rstack_front(rs4), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs26));
ASSERT_RESULT(rstack_front(rs47), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs29));
ASSERT(rstack_empty(rs15) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs10));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs11));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs34, rs43));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs29));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs11, rs19));
ASSERT(rstack_empty(rs18) == true);
ASSERT_RESULT(rstack_front(rs46), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs20));
ASSERT(rstack_empty(rs26) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs43));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs16));
ASSERT_RESULT(rstack_front(rs17), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs20));
ASSERT(rstack_empty(rs3) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs10));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs22));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs11, rs11));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs39));
ASSERT_RESULT(rstack_front(rs44), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs27));
ASSERT_RESULT(rstack_front(rs35), false, 0UL);
ASSERT_RESULT(rstack_front(rs37), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs46));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs34));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs5));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_6.result.out", rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs16));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs29));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs33));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_39.result.out", rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs34, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs48));
ASSERT(rstack_empty(rs41) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs44));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_21.result.out", rs18));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_23.result.out", rs42));
ASSERT_RESULT(rstack_front(rs16), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs44));
ASSERT(rstack_empty(rs11) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs20, rs17));
ASSERT_RESULT(rstack_front(rs17), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs34, rs46));
ASSERT(rstack_empty(rs43) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs8));
ASSERT(rstack_empty(rs16) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs12));
ASSERT_RESULT(rstack_front(rs49), false, 0UL);
ASSERT_RESULT(rstack_front(rs37), false, 0UL);
ASSERT_RESULT(rstack_front(rs35), false, 0UL);
ASSERT(rstack_empty(rs15) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs24));
ASSERT_RESULT(rstack_front(rs12), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_8.result.out", rs43));
ASSERT_RESULT(rstack_front(rs48), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs25));
ASSERT(rstack_empty(rs49) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs15));
ASSERT_RESULT(rstack_front(rs35), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs35));
ASSERT_RESULT(rstack_front(rs44), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs17));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs20, rs6));
ASSERT_RESULT(rstack_front(rs19), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs3));
ASSERT_RESULT(rstack_front(rs10), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs42));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs17));
ASSERT_RESULT(rstack_front(rs3), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs3));
ASSERT_RESULT(rstack_front(rs47), false, 0UL);
ASSERT_RESULT(rstack_front(rs5), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs11));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_0.result.out", rs13));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs20, rs26));
ASSERT(rstack_empty(rs19) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs21));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs8));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_17.result.out", rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs12));
ASSERT(rstack_empty(rs47) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs26));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs44));
ASSERT_RESULT(rstack_front(rs15), false, 0UL);
ASSERT_RESULT(rstack_front(rs47), false, 0UL);
ASSERT_RESULT(rstack_front(rs38), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs33));
ASSERT(rstack_empty(rs14) == true);
ASSERT(rstack_empty(rs30) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs28));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs19));
ASSERT_RESULT(rstack_front(rs33), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs15));
ASSERT_RESULT(rstack_front(rs1), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs46));
ASSERT_RESULT(rstack_front(rs41), false, 0UL);
ASSERT(rstack_empty(rs11) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs14));
ASSERT(rstack_empty(rs12) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs17));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs44));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs22));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs2));
ASSERT(rstack_empty(rs0) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs31, rs26));
ASSERT_RESULT(rstack_front(rs47), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs25));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs39, rs17));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs44));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs21));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs40));
ASSERT(rstack_empty(rs14) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs18));
ASSERT(rstack_empty(rs33) == true);
ASSERT(rstack_empty(rs47) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs16));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs44));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs13));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_49.result.out", rs3));
ASSERT_RESULT(rstack_front(rs35), false, 0UL);
ASSERT_RESULT(rstack_front(rs4), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs39));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs24));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_15.result.out", rs42));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs22));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs31, rs16));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs22));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs49));
ASSERT(rstack_empty(rs42) == true);
ASSERT_RESULT(rstack_front(rs6), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs31));
ASSERT(rstack_empty(rs36) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs34, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs36));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs34));
ASSERT_RESULT(rstack_front(rs36), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs31, rs30));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs6));
ASSERT_RESULT(rstack_front(rs41), false, 0UL);
ASSERT_RESULT(rstack_front(rs14), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs20));
ASSERT(rstack_empty(rs24) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs34));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs2));
ASSERT_RESULT(rstack_front(rs44), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs34, rs37));
ASSERT_RESULT(rstack_front(rs12), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs20));
ASSERT_RESULT(rstack_front(rs21), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs38));
ASSERT_RESULT(rstack_front(rs40), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs34, rs11));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs30));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs45));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs47));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs43));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs10));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs30));
ASSERT_RESULT(rstack_front(rs5), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs25));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs26));
ASSERT_RESULT(rstack_front(rs42), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs7));
ASSERT_RESULT(rstack_front(rs12), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_46.result.out", rs22));
ASSERT_RESULT(rstack_front(rs19), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs38));
ASSERT(rstack_empty(rs21) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs16));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs4));
ASSERT_RESULT(rstack_front(rs38), false, 0UL);
ASSERT(rstack_empty(rs37) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs39, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs46));
ASSERT_RESULT(rstack_front(rs15), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs6));
ASSERT_RESULT(rstack_front(rs29), false, 0UL);
ASSERT_RESULT(rstack_front(rs14), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs48));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_12.result.out", rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs39, rs47));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs44, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs49));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs34, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs36));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs35));
ASSERT_RESULT(rstack_front(rs8), false, 0UL);
ASSERT_RESULT(rstack_front(rs37), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs9));
ASSERT_RESULT(rstack_front(rs12), false, 0UL);
ASSERT_RESULT(rstack_front(rs49), false, 0UL);
ASSERT_RESULT(rstack_front(rs9), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs31, rs10));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs25));
ASSERT_RESULT(rstack_front(rs47), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs29));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs37));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs37));
ASSERT(rstack_empty(rs39) == true);
ASSERT_RESULT(rstack_front(rs29), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs39, rs45));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs44));
ASSERT_RESULT(rstack_front(rs4), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs16));
ASSERT(rstack_empty(rs26) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs39));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs28));
ASSERT_RESULT(rstack_front(rs15), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs25));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs9));
ASSERT_RESULT(rstack_front(rs16), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs15));
ASSERT_RESULT(rstack_front(rs7), false, 0UL);
ASSERT_RESULT(rstack_front(rs4), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs6));
ASSERT_RESULT(rstack_front(rs14), false, 0UL);
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs21));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs40));
ASSERT_RESULT(rstack_front(rs14), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs28));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs8));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_13.result.out", rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs31));
ASSERT_RESULT(rstack_front(rs29), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs38));
ASSERT_RESULT(rstack_front(rs42), false, 0UL);
ASSERT_RESULT(rstack_front(rs13), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs11, rs21));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs28));
ASSERT_RESULT(rstack_front(rs28), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs43));
ASSERT_RESULT(rstack_front(rs1), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs9));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_10.result.out", rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs20));
ASSERT_RESULT(rstack_front(rs38), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs34));
ASSERT_RESULT(rstack_front(rs44), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs48));
ASSERT_RESULT(rstack_front(rs13), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs48));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test43_40.result.out", rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs14));
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs34, rs23));
ASSERT_RESULT(rstack_front(rs5), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs20));
ASSERT_RESULT(rstack_front(rs27), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs36));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs7));
ASSERT_RESULT(rstack_front(rs17), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs34));
ASSERT(rstack_empty(rs1) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs39, rs8));
ASSERT_RESULT(rstack_front(rs37), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs42));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs21));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs16));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs31, rs7));
ASSERT(rstack_empty(rs30) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs47));
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
rstack_delete(rs0);
rstack_delete(rs1);
rstack_delete(rs2);
rstack_delete(rs3);
rstack_delete(rs4);
rstack_delete(rs5);
rstack_delete(rs6);
rstack_delete(rs7);
rstack_delete(rs8);
rstack_delete(rs9);
rstack_delete(rs10);
rstack_delete(rs11);
rstack_delete(rs12);
rstack_delete(rs13);
rstack_delete(rs14);
rstack_delete(rs15);
rstack_delete(rs16);
rstack_delete(rs17);
rstack_delete(rs18);
rstack_delete(rs19);
rstack_delete(rs20);
rstack_delete(rs21);
rstack_delete(rs22);
rstack_delete(rs23);
rstack_delete(rs24);
rstack_delete(rs25);
rstack_delete(rs26);
rstack_delete(rs27);
rstack_delete(rs28);
rstack_delete(rs29);
rstack_delete(rs30);
rstack_delete(rs31);
rstack_delete(rs32);
rstack_delete(rs33);
rstack_delete(rs34);
rstack_delete(rs35);
rstack_delete(rs36);
rstack_delete(rs37);
rstack_delete(rs38);
rstack_delete(rs39);
rstack_delete(rs40);
rstack_delete(rs41);
rstack_delete(rs42);
rstack_delete(rs43);
rstack_delete(rs44);
rstack_delete(rs45);
rstack_delete(rs46);
rstack_delete(rs47);
rstack_delete(rs48);
rstack_delete(rs49);
    
    return PASS;
}