
#include "rstack.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>

#undef NDEBUG

/** MAKRA SKRACAJĄCE IMPLEMENTACJĘ TESTÓW **/

// To są możliwe wyniki testu.
#define PASS 0
#define FAIL 1
#define WRONG_TEST 2

// Oblicza liczbę elementów tablicy x.
#define SIZE(x) (sizeof x / sizeof x[0])

#define ASSERT(f)            \
  do {                       \
    if (!(f))                \
      return FAIL;           \
  } while (0)

#define ASSERT_RESULT(c, f, ...)          \
  do {                                    \
    result_t r = c;                       \
    if (r.flag != (f))                    \
      return FAIL;                        \
    if ((f) && r.value != __VA_ARGS__ -0) \
      return FAIL;                        \
  } while (0)

#define CHECK_IF_NO_ERROR(f) \
  do {                       \
    if ((f) != 0)            \
      return FAIL;           \
  } while (0)

#define V(code, where) (((unsigned long)code) << (3 * where))

int test46(void) {
rstack_t* rs0 = rstack_new();
rstack_t* rs1 = rstack_new();
rstack_t* rs2 = rstack_new();
rstack_t* rs3 = rstack_new();
rstack_t* rs4 = rstack_new();
rstack_t* rs5 = rstack_new();
rstack_t* rs6 = rstack_new();
rstack_t* rs7 = rstack_new();
rstack_t* rs8 = rstack_new();
rstack_t* rs9 = rstack_new();
rstack_t* rs10 = rstack_new();
rstack_t* rs11 = rstack_new();
rstack_t* rs12 = rstack_new();
rstack_t* rs13 = rstack_new();
rstack_t* rs14 = rstack_new();
rstack_t* rs15 = rstack_new();
rstack_t* rs16 = rstack_new();
rstack_t* rs17 = rstack_new();
rstack_t* rs18 = rstack_new();
rstack_t* rs19 = rstack_new();
rstack_t* rs20 = rstack_new();
rstack_t* rs21 = rstack_new();
rstack_t* rs22 = rstack_new();
rstack_t* rs23 = rstack_new();
rstack_t* rs24 = rstack_new();
rstack_t* rs25 = rstack_new();
rstack_t* rs26 = rstack_new();
rstack_t* rs27 = rstack_new();
rstack_t* rs28 = rstack_new();
rstack_t* rs29 = rstack_new();
rstack_t* rs30 = rstack_new();
rstack_t* rs31 = rstack_new();
rstack_t* rs32 = rstack_new();
rstack_t* rs33 = rstack_new();
rstack_t* rs34 = rstack_new();
rstack_t* rs35 = rstack_new();
rstack_t* rs36 = rstack_new();
rstack_t* rs37 = rstack_new();
rstack_t* rs38 = rstack_new();
rstack_t* rs39 = rstack_new();
rstack_t* rs40 = rstack_new();
rstack_t* rs41 = rstack_new();
rstack_t* rs42 = rstack_new();
rstack_t* rs43 = rstack_new();
rstack_t* rs44 = rstack_new();
rstack_t* rs45 = rstack_new();
rstack_t* rs46 = rstack_new();
rstack_t* rs47 = rstack_new();
rstack_t* rs48 = rstack_new();
rstack_t* rs49 = rstack_new();
rstack_t* rs50 = rstack_new();
rstack_t* rs51 = rstack_new();
rstack_t* rs52 = rstack_new();
rstack_t* rs53 = rstack_new();
rstack_t* rs54 = rstack_new();
rstack_t* rs55 = rstack_new();
rstack_t* rs56 = rstack_new();
rstack_t* rs57 = rstack_new();
rstack_t* rs58 = rstack_new();
rstack_t* rs59 = rstack_new();
rstack_t* rs60 = rstack_new();
rstack_t* rs61 = rstack_new();
rstack_t* rs62 = rstack_new();
rstack_t* rs63 = rstack_new();
rstack_t* rs64 = rstack_new();
rstack_t* rs65 = rstack_new();
rstack_t* rs66 = rstack_new();
rstack_t* rs67 = rstack_new();
rstack_t* rs68 = rstack_new();
rstack_t* rs69 = rstack_new();
rstack_t* rs70 = rstack_new();
rstack_t* rs71 = rstack_new();
rstack_t* rs72 = rstack_new();
rstack_t* rs73 = rstack_new();
rstack_t* rs74 = rstack_new();
rstack_t* rs75 = rstack_new();
rstack_t* rs76 = rstack_new();
rstack_t* rs77 = rstack_new();
rstack_t* rs78 = rstack_new();
rstack_t* rs79 = rstack_new();
rstack_t* rs80 = rstack_new();
rstack_t* rs81 = rstack_new();
rstack_t* rs82 = rstack_new();
rstack_t* rs83 = rstack_new();
rstack_t* rs84 = rstack_new();
rstack_t* rs85 = rstack_new();
rstack_t* rs86 = rstack_new();
rstack_t* rs87 = rstack_new();
rstack_t* rs88 = rstack_new();
rstack_t* rs89 = rstack_new();
rstack_t* rs90 = rstack_new();
rstack_t* rs91 = rstack_new();
rstack_t* rs92 = rstack_new();
rstack_t* rs93 = rstack_new();
rstack_t* rs94 = rstack_new();
rstack_t* rs95 = rstack_new();
rstack_t* rs96 = rstack_new();
rstack_t* rs97 = rstack_new();
rstack_t* rs98 = rstack_new();
rstack_t* rs99 = rstack_new();
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_47.result.out", rs87));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_16.result.out", rs47));
ASSERT(rstack_empty(rs26) == true);
ASSERT_RESULT(rstack_front(rs18), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_15.result.out", rs78));
ASSERT(rstack_empty(rs19) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs98));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_73.result.out", rs97));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_12.result.out", rs43));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_42.result.out", rs36));
ASSERT_RESULT(rstack_front(rs92), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_96.result.out", rs45));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_62.result.out", rs54));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_49.result.out", rs42));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_56.result.out", rs33));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_26.result.out", rs93));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_53.result.out", rs25));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_44.result.out", rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs33));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_19.result.out", rs9));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_80.result.out", rs8));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_23.result.out", rs25));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_24.result.out", rs22));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_74.result.out", rs74));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_41.result.out", rs8));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_33.result.out", rs50));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_81.result.out", rs34));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_28.result.out", rs83));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_8.result.out", rs15));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_13.result.out", rs10));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_78.result.out", rs13));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_88.result.out", rs27));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_94.result.out", rs40));
ASSERT(rstack_empty(rs62) == true);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_52.result.out", rs14));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_4.result.out", rs47));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_77.result.out", rs95));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_95.result.out", rs96));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_27.result.out", rs9));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_67.result.out", rs6));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_75.result.out", rs22));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_31.result.out", rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs45));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_83.result.out", rs48));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_40.result.out", rs28));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs87, rs62));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_45.result.out", rs94));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_30.result.out", rs78));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_86.result.out", rs16));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_10.result.out", rs23));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_3.result.out", rs93));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_48.result.out", rs22));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_5.result.out", rs89));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_35.result.out", rs16));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_11.result.out", rs68));
ASSERT_RESULT(rstack_front(rs9), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs85, rs97));
ASSERT_RESULT(rstack_front(rs31), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_34.result.out", rs20));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_98.result.out", rs49));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_87.result.out", rs17));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_37.result.out", rs29));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_71.result.out", rs61));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_99.result.out", rs76));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs66));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_58.result.out", rs39));
ASSERT_RESULT(rstack_front(rs96), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_32.result.out", rs44));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_57.result.out", rs80));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_97.result.out", rs77));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_91.result.out", rs7));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_90.result.out", rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs52, rs15));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_25.result.out", rs42));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_89.result.out", rs47));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_59.result.out", rs43));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_38.result.out", rs15));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_85.result.out", rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs77));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_51.result.out", rs44));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_70.result.out", rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs56, rs10));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_9.result.out", rs98));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_76.result.out", rs79));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_29.result.out", rs63));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_2.result.out", rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs95));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs10));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_14.result.out", rs18));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_93.result.out", rs63));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_92.result.out", rs79));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_21.result.out", rs38));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_46.result.out", rs94));
ASSERT_RESULT(rstack_front(rs12), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_84.result.out", rs82));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_61.result.out", rs29));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_55.result.out", rs36));
ASSERT_RESULT(rstack_front(rs39), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_0.result.out", rs88));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs78));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_65.result.out", rs31));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_50.result.out", rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs68, rs55));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs63, rs62));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_22.result.out", rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs83, rs52));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_17.result.out", rs65));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_43.result.out", rs96));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs60, rs81));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs1));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_20.result.out", rs11));
ASSERT_RESULT(rstack_front(rs28), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs99));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_69.result.out", rs15));
ASSERT_RESULT(rstack_front(rs46), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_1.result.out", rs59));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs67));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs77, rs66));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_54.result.out", rs58));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_64.result.out", rs29));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs57, rs40));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_63.result.out", rs92));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs57));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_82.result.out", rs32));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_39.result.out", rs7));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_36.result.out", rs67));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_68.result.out", rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs86, rs84));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_18.result.out", rs9));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_66.result.out", rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs60, rs47));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_6.result.out", rs80));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_79.result.out", rs88));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_72.result.out", rs31));
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_7.result.out", rs40));
CHECK_IF_NO_ERROR(rstack_write("tests/output/test46_60.result.out", rs86));
rstack_delete(rs95);
rstack_delete(rs96);
rstack_delete(rs97);
rstack_delete(rs98);
rstack_delete(rs99);
ASSERT_RESULT(rstack_front(rs91), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs75, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs72, rs11));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs34));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs9));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs60, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs50));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs48));
ASSERT(rstack_empty(rs58) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs76, rs55));
ASSERT_RESULT(rstack_front(rs6), false, 0UL);
ASSERT_RESULT(rstack_front(rs7), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs66));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs78));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs78));
ASSERT(rstack_empty(rs39) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs45));
ASSERT_RESULT(rstack_front(rs85), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs31, rs51));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs78, rs26));
ASSERT(rstack_empty(rs57) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs83, rs21));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs84));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs60, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs58, rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs72));
ASSERT_RESULT(rstack_front(rs31), false, 0UL);
ASSERT_RESULT(rstack_front(rs58), false, 0UL);
ASSERT_RESULT(rstack_front(rs33), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs61, rs56));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs87, rs34));
ASSERT_RESULT(rstack_front(rs77), false, 0UL);
ASSERT_RESULT(rstack_front(rs39), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs91, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs68, rs94));
ASSERT_RESULT(rstack_front(rs27), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs82, rs76));
rstack_delete(rs90);
rstack_delete(rs91);
rstack_delete(rs92);
rstack_delete(rs93);
rstack_delete(rs94);
ASSERT(rstack_empty(rs79) == true);
ASSERT(rstack_empty(rs33) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs70, rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs34, rs83));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs71, rs11));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs34));
ASSERT(rstack_empty(rs58) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs84, rs57));
ASSERT_RESULT(rstack_front(rs78), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs75));
ASSERT(rstack_empty(rs1) == true);
ASSERT(rstack_empty(rs59) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs69, rs85));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs29));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs14));
ASSERT_RESULT(rstack_front(rs5), false, 0UL);
ASSERT_RESULT(rstack_front(rs12), false, 0UL);
ASSERT_RESULT(rstack_front(rs43), false, 0UL);
ASSERT(rstack_empty(rs67) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs54));
ASSERT(rstack_empty(rs1) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs34, rs38));
ASSERT_RESULT(rstack_front(rs32), false, 0UL);
ASSERT(rstack_empty(rs64) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs11, rs30));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs52));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs60, rs39));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs84, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs89, rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs25));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs17));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs10));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs88, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs46, rs66));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs88, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs46));
rstack_delete(rs85);
rstack_delete(rs86);
rstack_delete(rs87);
rstack_delete(rs88);
rstack_delete(rs89);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs3));
ASSERT(rstack_empty(rs83) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs17));
ASSERT_RESULT(rstack_front(rs5), false, 0UL);
ASSERT(rstack_empty(rs31) == true);
ASSERT_RESULT(rstack_front(rs62), false, 0UL);
ASSERT_RESULT(rstack_front(rs61), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs58, rs60));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs55, rs78));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs54));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs56));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs74));
ASSERT_RESULT(rstack_front(rs76), false, 0UL);
ASSERT_RESULT(rstack_front(rs70), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs83, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs12));
ASSERT(rstack_empty(rs25) == true);
ASSERT(rstack_empty(rs55) == true);
ASSERT_RESULT(rstack_front(rs7), false, 0UL);
ASSERT_RESULT(rstack_front(rs77), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs42));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs34, rs84));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs74, rs62));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs62, rs76));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs82));
ASSERT_RESULT(rstack_front(rs10), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs28));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs57));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs34));
ASSERT_RESULT(rstack_front(rs39), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs43));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs82, rs56));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs77));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs43));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs60, rs27));
rstack_delete(rs80);
rstack_delete(rs81);
rstack_delete(rs82);
rstack_delete(rs83);
rstack_delete(rs84);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs53, rs77));
ASSERT(rstack_empty(rs20) == true);
ASSERT_RESULT(rstack_front(rs56), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs50));
ASSERT(rstack_empty(rs9) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs64, rs21));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs62, rs12));
ASSERT(rstack_empty(rs40) == true);
ASSERT_RESULT(rstack_front(rs32), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs75, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs14));
ASSERT(rstack_empty(rs65) == true);
ASSERT(rstack_empty(rs73) == true);
ASSERT(rstack_empty(rs19) == true);
ASSERT_RESULT(rstack_front(rs23), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs71));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs61, rs79));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs69, rs77));
ASSERT_RESULT(rstack_front(rs18), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs51, rs25));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs52));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs55, rs36));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs71, rs78));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs67));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs57));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs29));
ASSERT(rstack_empty(rs50) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs54, rs63));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs77, rs2));
ASSERT_RESULT(rstack_front(rs21), false, 0UL);
ASSERT_RESULT(rstack_front(rs34), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs77, rs78));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs64, rs46));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs55, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs74, rs40));
rstack_delete(rs75);
rstack_delete(rs76);
rstack_delete(rs77);
rstack_delete(rs78);
rstack_delete(rs79);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs36));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs68));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs66));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs56));
ASSERT_RESULT(rstack_front(rs33), false, 0UL);
ASSERT(rstack_empty(rs55) == true);
ASSERT_RESULT(rstack_front(rs1), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs58, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs64));
ASSERT_RESULT(rstack_front(rs10), false, 0UL);
ASSERT_RESULT(rstack_front(rs22), false, 0UL);
ASSERT_RESULT(rstack_front(rs74), false, 0UL);
ASSERT_RESULT(rstack_front(rs13), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs53, rs74));
ASSERT(rstack_empty(rs0) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs37));
ASSERT_RESULT(rstack_front(rs59), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs4));
ASSERT_RESULT(rstack_front(rs69), false, 0UL);
ASSERT_RESULT(rstack_front(rs54), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs60));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs20, rs65));
ASSERT(rstack_empty(rs29) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs62));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs74, rs64));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs64));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs72, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs53, rs36));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs63, rs47));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs51));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs64));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs38));
ASSERT(rstack_empty(rs35) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs47));
rstack_delete(rs70);
rstack_delete(rs71);
rstack_delete(rs72);
rstack_delete(rs73);
rstack_delete(rs74);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs64, rs44));
ASSERT_RESULT(rstack_front(rs26), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs39, rs59));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs56));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs68));
ASSERT_RESULT(rstack_front(rs59), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs51, rs32));
ASSERT_RESULT(rstack_front(rs53), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs59));
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
ASSERT(rstack_empty(rs45) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs69, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs42));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs52));
ASSERT_RESULT(rstack_front(rs10), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs68));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs59));
ASSERT(rstack_empty(rs62) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs30));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs61, rs58));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs57, rs34));
ASSERT(rstack_empty(rs69) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs11));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs49));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs64, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs57));
ASSERT_RESULT(rstack_front(rs27), false, 0UL);
ASSERT_RESULT(rstack_front(rs49), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs45));
ASSERT_RESULT(rstack_front(rs12), false, 0UL);
ASSERT_RESULT(rstack_front(rs37), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs52));
ASSERT(rstack_empty(rs35) == true);
rstack_delete(rs65);
rstack_delete(rs66);
rstack_delete(rs67);
rstack_delete(rs68);
rstack_delete(rs69);
ASSERT_RESULT(rstack_front(rs51), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs59, rs46));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs52));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs52));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs54));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs56));
ASSERT(rstack_empty(rs5) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs38));
ASSERT_RESULT(rstack_front(rs28), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs50));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs63));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs47));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs48));
ASSERT_RESULT(rstack_front(rs42), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs56, rs46));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs63, rs14));
ASSERT(rstack_empty(rs35) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs37));
ASSERT_RESULT(rstack_front(rs64), false, 0UL);
ASSERT_RESULT(rstack_front(rs21), false, 0UL);
ASSERT(rstack_empty(rs26) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs40));
ASSERT_RESULT(rstack_front(rs52), false, 0UL);
ASSERT_RESULT(rstack_front(rs56), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs50, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs46));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs63));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs37));
ASSERT_RESULT(rstack_front(rs62), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs53, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs9));
ASSERT_RESULT(rstack_front(rs41), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs18));
ASSERT_RESULT(rstack_front(rs32), false, 0UL);
rstack_delete(rs60);
rstack_delete(rs61);
rstack_delete(rs62);
rstack_delete(rs63);
rstack_delete(rs64);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs36));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs53, rs43));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs21));
ASSERT_RESULT(rstack_front(rs38), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs55, rs22));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs2));
ASSERT_RESULT(rstack_front(rs3), false, 0UL);
ASSERT(rstack_empty(rs16) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs39, rs24));
ASSERT_RESULT(rstack_front(rs28), false, 0UL);
ASSERT_RESULT(rstack_front(rs38), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs11, rs56));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs29));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs48));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs16));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs31, rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs37));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs34, rs59));
ASSERT_RESULT(rstack_front(rs24), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs29));
ASSERT(rstack_empty(rs23) == true);
ASSERT(rstack_empty(rs36) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs40));
ASSERT_RESULT(rstack_front(rs51), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs58));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs9));
ASSERT_RESULT(rstack_front(rs39), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs20, rs45));
ASSERT_RESULT(rstack_front(rs26), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs59, rs25));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs52, rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs48, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs9));
ASSERT(rstack_empty(rs34) == true);
ASSERT(rstack_empty(rs20) == true);
rstack_delete(rs55);
rstack_delete(rs56);
rstack_delete(rs57);
rstack_delete(rs58);
rstack_delete(rs59);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs47));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs4));
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
ASSERT_RESULT(rstack_front(rs28), false, 0UL);
ASSERT(rstack_empty(rs41) == true);
ASSERT_RESULT(rstack_front(rs37), false, 0UL);
ASSERT_RESULT(rstack_front(rs54), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs21));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs51));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs39));
ASSERT_RESULT(rstack_front(rs33), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs11));
ASSERT_RESULT(rstack_front(rs13), false, 0UL);
ASSERT_RESULT(rstack_front(rs41), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs7));
ASSERT_RESULT(rstack_front(rs5), false, 0UL);
ASSERT(rstack_empty(rs45) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs45, rs44));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs42, rs43));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs37));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs34));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs11));
ASSERT(rstack_empty(rs5) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs53, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs18));
ASSERT(rstack_empty(rs51) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs52));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs34));
ASSERT_RESULT(rstack_front(rs42), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs9));
rstack_delete(rs50);
rstack_delete(rs51);
rstack_delete(rs52);
rstack_delete(rs53);
rstack_delete(rs54);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs47));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs48));
ASSERT(rstack_empty(rs15) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs30));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs34));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs38, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs39));
ASSERT_RESULT(rstack_front(rs11), false, 0UL);
ASSERT_RESULT(rstack_front(rs11), false, 0UL);
ASSERT(rstack_empty(rs34) == true);
ASSERT(rstack_empty(rs48) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs47, rs5));
ASSERT(rstack_empty(rs9) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs32));
ASSERT_RESULT(rstack_front(rs38), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs34));
ASSERT_RESULT(rstack_front(rs39), false, 0UL);
ASSERT_RESULT(rstack_front(rs3), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs35));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs24));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs43));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs40));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs46));
ASSERT(rstack_empty(rs42) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs49, rs40));
ASSERT_RESULT(rstack_front(rs20), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs32, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs21));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs34));
ASSERT_RESULT(rstack_front(rs40), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs17));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs45));
ASSERT_RESULT(rstack_front(rs24), false, 0UL);
rstack_delete(rs45);
rstack_delete(rs46);
rstack_delete(rs47);
rstack_delete(rs48);
rstack_delete(rs49);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs21));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs34));
ASSERT(rstack_empty(rs31) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs30));
ASSERT(rstack_empty(rs13) == true);
ASSERT_RESULT(rstack_front(rs22), false, 0UL);
ASSERT_RESULT(rstack_front(rs27), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs26));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs23));
ASSERT_RESULT(rstack_front(rs9), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs42));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs39));
ASSERT_RESULT(rstack_front(rs28), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs28));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs19));
ASSERT_RESULT(rstack_front(rs25), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs28));
ASSERT_RESULT(rstack_front(rs16), false, 0UL);
ASSERT(rstack_empty(rs12) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs30));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs41, rs41));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs11));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs26));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs40, rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs31, rs29));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs30, rs35));
ASSERT_RESULT(rstack_front(rs12), false, 0UL);
ASSERT(rstack_empty(rs44) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs43, rs33));
ASSERT_RESULT(rstack_front(rs4), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs43));
ASSERT_RESULT(rstack_front(rs10), false, 0UL);
rstack_delete(rs40);
rstack_delete(rs41);
rstack_delete(rs42);
rstack_delete(rs43);
rstack_delete(rs44);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs22));
ASSERT_RESULT(rstack_front(rs7), false, 0UL);
ASSERT_RESULT(rstack_front(rs11), false, 0UL);
ASSERT_RESULT(rstack_front(rs39), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs25));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs25));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs0));
ASSERT(rstack_empty(rs34) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs39));
ASSERT_RESULT(rstack_front(rs36), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs11));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs16));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs37, rs38));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs11));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs36));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs36, rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs29));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs28));
ASSERT(rstack_empty(rs27) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs13));
ASSERT(rstack_empty(rs18) == true);
ASSERT(rstack_empty(rs13) == true);
ASSERT(rstack_empty(rs31) == true);
ASSERT(rstack_empty(rs24) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs9));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs33, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs37));
ASSERT(rstack_empty(rs14) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs34, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs17));
ASSERT(rstack_empty(rs24) == true);
ASSERT_RESULT(rstack_front(rs1), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs31));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs35, rs20));
rstack_delete(rs35);
rstack_delete(rs36);
rstack_delete(rs37);
rstack_delete(rs38);
rstack_delete(rs39);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs32));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs31));
ASSERT(rstack_empty(rs8) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs29, rs21));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs28));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs9));
ASSERT_RESULT(rstack_front(rs16), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs29));
ASSERT_RESULT(rstack_front(rs21), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs30));
ASSERT(rstack_empty(rs13) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs20));
ASSERT_RESULT(rstack_front(rs2), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs33));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs4));
ASSERT_RESULT(rstack_front(rs15), false, 0UL);
ASSERT_RESULT(rstack_front(rs26), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs28));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs22, rs14));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs22));
ASSERT_RESULT(rstack_front(rs3), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs30));
ASSERT_RESULT(rstack_front(rs16), false, 0UL);
ASSERT(rstack_empty(rs23) == true);
ASSERT_RESULT(rstack_front(rs30), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs18));
ASSERT_RESULT(rstack_front(rs26), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs30));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs31));
ASSERT_RESULT(rstack_front(rs4), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs9));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs13));
rstack_delete(rs30);
rstack_delete(rs31);
rstack_delete(rs32);
rstack_delete(rs33);
rstack_delete(rs34);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs17));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs27, rs11));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs9));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs27));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs11, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs25, rs25));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs2));
ASSERT_RESULT(rstack_front(rs6), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs23));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs16));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs0));
ASSERT(rstack_empty(rs1) == true);
ASSERT_RESULT(rstack_front(rs18), false, 0UL);
ASSERT(rstack_empty(rs26) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs28, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs29));
ASSERT(rstack_empty(rs1) == true);
ASSERT_RESULT(rstack_front(rs18), false, 0UL);
ASSERT_RESULT(rstack_front(rs14), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs21));
ASSERT_RESULT(rstack_front(rs10), false, 0UL);
ASSERT_RESULT(rstack_front(rs13), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs28));
ASSERT(rstack_empty(rs25) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs13));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs21));
ASSERT_RESULT(rstack_front(rs14), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs13));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs3));
ASSERT_RESULT(rstack_front(rs23), false, 0UL);
ASSERT(rstack_empty(rs7) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs16));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs26, rs22));
rstack_delete(rs25);
rstack_delete(rs26);
rstack_delete(rs27);
rstack_delete(rs28);
rstack_delete(rs29);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs3));
ASSERT(rstack_empty(rs2) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs0));
ASSERT_RESULT(rstack_front(rs7), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs20));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs16));
ASSERT_RESULT(rstack_front(rs14), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs15));
ASSERT(rstack_empty(rs12) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs21));
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
ASSERT(rstack_empty(rs22) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs21, rs22));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs20, rs20));
ASSERT(rstack_empty(rs9) == true);
ASSERT(rstack_empty(rs7) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs12));
ASSERT(rstack_empty(rs1) == true);
ASSERT_RESULT(rstack_front(rs18), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs23, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs16, rs14));
ASSERT_RESULT(rstack_front(rs23), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs8));
ASSERT(rstack_empty(rs19) == true);
ASSERT_RESULT(rstack_front(rs19), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs11, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs24, rs12));
rstack_delete(rs20);
rstack_delete(rs21);
rstack_delete(rs22);
rstack_delete(rs23);
rstack_delete(rs24);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs15));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs0));
ASSERT(rstack_empty(rs10) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs19));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs11, rs18));
ASSERT_RESULT(rstack_front(rs3), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs18));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs17, rs16));
ASSERT(rstack_empty(rs15) == true);
ASSERT_RESULT(rstack_front(rs10), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs8));
ASSERT_RESULT(rstack_front(rs3), false, 0UL);
ASSERT_RESULT(rstack_front(rs3), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs11, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs18, rs11));
ASSERT_RESULT(rstack_front(rs7), false, 0UL);
ASSERT_RESULT(rstack_front(rs19), false, 0UL);
ASSERT_RESULT(rstack_front(rs2), false, 0UL);
ASSERT(rstack_empty(rs18) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs19, rs11));
ASSERT(rstack_empty(rs1) == true);
ASSERT_RESULT(rstack_front(rs17), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs9));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs15, rs17));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs10));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs10));
ASSERT(rstack_empty(rs4) == true);
rstack_delete(rs15);
rstack_delete(rs16);
rstack_delete(rs17);
rstack_delete(rs18);
rstack_delete(rs19);
ASSERT_RESULT(rstack_front(rs8), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs13));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs12));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs11));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs13));
ASSERT(rstack_empty(rs0) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs6));
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
ASSERT_RESULT(rstack_front(rs7), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs12, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs13));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs1));
ASSERT_RESULT(rstack_front(rs12), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs12));
ASSERT(rstack_empty(rs11) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs10, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs6));
ASSERT(rstack_empty(rs11) == true);
ASSERT_RESULT(rstack_front(rs1), false, 0UL);
ASSERT_RESULT(rstack_front(rs11), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs2));
ASSERT_RESULT(rstack_front(rs1), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs8));
ASSERT_RESULT(rstack_front(rs7), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs14, rs9));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs0));
ASSERT(rstack_empty(rs7) == true);
ASSERT_RESULT(rstack_front(rs10), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs13, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs6));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs6, rs4));
rstack_delete(rs10);
rstack_delete(rs11);
rstack_delete(rs12);
rstack_delete(rs13);
rstack_delete(rs14);
ASSERT(rstack_empty(rs5) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs6));
ASSERT(rstack_empty(rs2) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs1));
ASSERT(rstack_empty(rs7) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs7));
ASSERT(rstack_empty(rs0) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs8, rs7));
ASSERT_RESULT(rstack_front(rs9), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs1));
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs8));
ASSERT_RESULT(rstack_front(rs6), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs3));
ASSERT_RESULT(rstack_front(rs1), false, 0UL);
ASSERT_RESULT(rstack_front(rs9), false, 0UL);
ASSERT_RESULT(rstack_front(rs3), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs9, rs5));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs5));
ASSERT_RESULT(rstack_front(rs8), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs5, rs5));
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs9));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs8));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs7, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs7));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs0));
ASSERT(rstack_empty(rs4) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs6));
rstack_delete(rs5);
rstack_delete(rs6);
rstack_delete(rs7);
rstack_delete(rs8);
rstack_delete(rs9);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs4));
ASSERT(rstack_empty(rs2) == true);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs2));
ASSERT_RESULT(rstack_front(rs4), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs0));
ASSERT(rstack_empty(rs2) == true);
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs0));
ASSERT_RESULT(rstack_front(rs4), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs1));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs2));
ASSERT_RESULT(rstack_front(rs3), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs0));
ASSERT_RESULT(rstack_front(rs3), false, 0UL);
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
ASSERT_RESULT(rstack_front(rs0), false, 0UL);
ASSERT_RESULT(rstack_front(rs1), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs0, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs4));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs3));
ASSERT_RESULT(rstack_front(rs4), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs0));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs3, rs2));
ASSERT_RESULT(rstack_front(rs3), false, 0UL);
CHECK_IF_NO_ERROR(rstack_push_rstack(rs1, rs2));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs2, rs3));
CHECK_IF_NO_ERROR(rstack_push_rstack(rs4, rs0));
rstack_delete(rs0);
rstack_delete(rs1);
rstack_delete(rs2);
rstack_delete(rs3);
rstack_delete(rs4);
    
    return PASS;
}